// GENERATED by scripts/uplift/build-ship.mjs from assets-source/uplift/models/.
// Do not edit — drop or remove model files (and their .import.json) instead.
export const IMPORTED_KITS: ReadonlyArray<string> = [
];
